# References:
# https://some-natalie.dev/blog/kaniko-in-arc/
# https://dev.to/ipo/using-kaniko-to-build-and-publish-container-image-with-github-action-on-github-self-hosted-runners-d5m

name: Image Build
on:
  workflow_dispatch:
  schedule:
  - cron: "0 21 1 * *"
  push:
    paths-ignore:
    - .github/**
    - README.md
    branches:
    - master

jobs:
  build:
    runs-on: arc-runner-${{ github.event.repository.name }}
    container:
      image: gcr.io/kaniko-project/executor:debug
    permissions:
      contents: read
      packages: write
    steps:
    - name: Set tag
      run: |
        VERSION=$(wget -O - https://api.github.com/repos/tailscale/tailscale/releases/latest | grep tag_name | cut -d '"' -f 4 | tr -d 'v')
        echo VERSION_LONG=$VERSION | tee -a "$GITHUB_ENV"
        echo VERSION_SHORT=$(echo $VERSION | cut -d '.' -f 1-2)
        echo TAG=$(date -u +'%Y%m%d.%H%M') | tee -a "$GITHUB_ENV"

    - name: Build and release container
      run: |
        cat > $DOCKER_CONFIG/config.json <<EOF
        {
          "auths": {
            "ghcr.io": {
              "auth": "$(echo -n ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} | base64 -w0)"
            }
          }
        }
        EOF

        TARGETARCH=$(arch)
        TARGETARCH=${TARGETARCH/x86_64/amd64} && TARGETARCH=${TARGETARCH/aarch64/arm64}

        /kaniko/executor \
          --dockerfile="./Containerfile" \
          --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}" \
          --destination="ghcr.io/${{ github.repository }}:v$VERSION_LONG.$TAG" \
          --build-arg VERSION_LONG=$VERSION_LONG \
          --build-arg VERSION_SHORT=$VERSION_SHORT \
          --build-arg VERSION_GIT_HASH=${{ github.sha }} \
          --build-arg TARGETARCH= \
          --push-retry 3
